export const stats = [
  { label: "Total Subscribers", value: "12,847", change: "+8.2%", color: "blue" },
  { label: "Active Subscribers", value: "2,156", change: "+3.1%", color: "green" },
  { label: "Open Rate", value: "24.7%", change: "+1.2%", color: "green" },
  { label: "Click Rate", value: "3.2%", change: "-0.4%", color: "red" },
  { label: "Broadcasts Sent", value: "47", change: "+12", color: "blue" },
  { label: "Bounce Rate", value: "1.8%", change: "-0.1%", color: "green" },
];

export const subscribers = [
  { id: 1, name: "Alice Johnson", email: "alice@example.com", status: "active", subscribed: "2026-01-12", opens: 142 },
  { id: 2, name: "Bob Smith", email: "bob.smith@mail.com", status: "active", subscribed: "2026-02-08", opens: 89 },
  { id: 3, name: "Carol White", email: "carol.w@company.org", status: "active", subscribed: "2026-03-15", opens: 210 },
  { id: 4, name: "David Brown", email: "david.b@domain.net", status: "inactive", subscribed: "2025-11-20", opens: 12 },
  { id: 5, name: "Eva Martinez", email: "eva.martinez@test.io", status: "active", subscribed: "2026-04-01", opens: 67 },
  { id: 6, name: "Frank Wilson", email: "frank.wilson@web.dev", status: "bounced", subscribed: "2026-01-05", opens: 0 },
  { id: 7, name: "Grace Lee", email: "grace.lee@service.com", status: "active", subscribed: "2026-05-10", opens: 34 },
  { id: 8, name: "Henry Taylor", email: "henry.t@firm.co", status: "active", subscribed: "2025-09-14", opens: 521 },
  { id: 9, name: "Iris Chen", email: "iris.chen@startup.dev", status: "inactive", subscribed: "2026-03-22", opens: 8 },
  { id: 10, name: "Jack Davis", email: "jack.davis@inbox.com", status: "active", subscribed: "2026-06-01", opens: 19 },
];

export const broadcasts = [
  {
    id: 1,
    subject: "Welcome to our newsletter!",
    sent: "2026-06-01",
    recipients: 12450,
    opens: 3120,
    clicks: 410,
    status: "sent",
  },
  {
    id: 2,
    subject: "Summer Sale - 30% Off Everything",
    sent: "2026-05-28",
    recipients: 12380,
    opens: 4820,
    clicks: 890,
    status: "sent",
  },
  {
    id: 3,
    subject: "Your monthly digest — June Edition",
    sent: "2026-06-15",
    recipients: 12847,
    opens: 0,
    clicks: 0,
    status: "scheduled",
  },
  {
    id: 4,
    subject: "Product Launch: New Features Inside",
    sent: "2026-05-10",
    recipients: 12100,
    opens: 3650,
    clicks: 720,
    status: "sent",
  },
  {
    id: 5,
    subject: "We hit 10k subscribers! 🎉",
    sent: "2026-04-22",
    recipients: 10400,
    opens: 5400,
    clicks: 1200,
    status: "sent",
  },
  {
    id: 6,
    subject: "Quick survey: help us improve",
    sent: "2026-06-18",
    recipients: 12800,
    opens: 0,
    clicks: 0,
    status: "draft",
  },
  {
    id: 7,
    subject: "Re-engagement campaign",
    sent: "2026-03-05",
    recipients: 3500,
    opens: 420,
    clicks: 55,
    status: "sent",
  },
];
